// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe3MFd41DISc61rIxF-f3BbgZuNGQiw0c',
    appId: '1:631177011769:web:08a0f295e0920b12e663e8',
    messagingSenderId: '631177011769',
    projectId: 'kreatifmerkezi-f8ecc',
    authDomain: 'kreatifmerkezi-f8ecc.firebaseapp.com',
    storageBucket: 'kreatifmerkezi-f8ecc.appspot.com',
    measurementId: 'G-GH90LM0E3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG7G5qSNKwB1UOeVc2FPC85HaT6KlTEVo',
    appId: '1:631177011769:android:fe42122c02e8d8bbe663e8',
    messagingSenderId: '631177011769',
    projectId: 'kreatifmerkezi-f8ecc',
    storageBucket: 'kreatifmerkezi-f8ecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDENfBCZE3CVXR4dWIozKR8aHnW9IgP1DY',
    appId: '1:631177011769:ios:f1f97961a53d4561e663e8',
    messagingSenderId: '631177011769',
    projectId: 'kreatifmerkezi-f8ecc',
    storageBucket: 'kreatifmerkezi-f8ecc.appspot.com',
    iosClientId: '631177011769-9ujfsvrheto0690gqvfdkb26tbqda0v7.apps.googleusercontent.com',
    iosBundleId: 'com.kreatifmerkezi.rezervasyon',
  );
}
